[package]
edition = "2024"
name = "sha3"
version = "0.1.0"

[dependencies]

[dev-dependencies]
haste = "0.1.0-alpha.2"
hex = "0.4.3"
libcrux-sha3 = "0.0.7"

[profile.profiling]
debug = true
inherits = "release"

[[bench]]
harness = false
name = "main"
