name: Pull Request

on:
  pull_request:
    branches:
      - "main"
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - &checkout
        name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - &cache
        name: Cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # 2.8.2
      
      - name: Show CPU info
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: lscpu

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --workspace --verbose --all-features --no-fail-fast

  test-big-endian:
    name: Test Big-Endian and 32-bit arch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "s390x-unknown-linux-gnu", "i686-unknown-linux-gnu" ]
    steps:
      - *checkout
      - *cache

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          components: "rust-src"
          targets: "${{ matrix.target }}"
      
      - name: Install cargo cross
        uses: taiki-e/install-action@cfdb446e391c69574ebc316dfb7d7849ec12b940 # 2.68.8
        with:
          tool: cross@0.2.5
      
      - name: Test on ${{ matrix.target }}
        run: cross test --target ${{ matrix.target }}

  miri:
    name: Miri
    runs-on: "ubuntu-latest"
    steps:
      - *checkout
      - *cache

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: nightly
          components: "miri,rust-src"

      - name: Run miri test
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation"
        run: cargo miri t

  fmt:
    name: Rustfmt
    runs-on: "ubuntu-latest"
    steps:
      - *checkout
      - *cache

      # nightly is needed for the unstable rustfmt options specified in project rustfmt.toml
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: nightly
          components: "rustfmt"

      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: "ubuntu-latest"
    steps:
      - *checkout
      - *cache

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: "stable"
          components: "clippy"

      - name: Check Clippy
        run: cargo clippy --workspace --all-features --examples --lib -- -D warnings

  docs:
    name: Docs
    runs-on: "ubuntu-latest"
    env:
      # deny rustdoc warnings
      RUSTDOCFLAGS: -D warnings
    steps:
      - *checkout
      - *cache

        # nightly is needed for the unstable rustdoc options
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: nightly
          components: "rust-docs"

      - name: Check docs
        run: cargo doc --workspace --verbose --all-features --no-deps -Zunstable-options -Zrustdoc-scrape-examples
